`timescale 1ns/10ps

// 32-to-1 Multiplexer Bus for the CPU Datapath
// Routes data from one of the CPU registers or system inputs onto the main 32-bit bus
// based strictly on the 5-bit selection signal generated by the 32-to-5 encoder.
module bus (
    output [31:0] BusMuxOut, // The selected 32-bit data broadcasted directly to the Datapath
    input [4:0] sel,         // 5-bit selection code driven by the encoder
    
    // 32-bit data inputs from the 16 General Purpose Registers
    input [31:0] R0in, R1in, R2in, R3in, R4in, R5in, R6in, R7in,
    input [31:0] R8in, R9in, R10in, R11in, R12in, R13in, R14in, R15in,
    
    // 32-bit data inputs from Special Purpose Registers and ALU output registers
    input [31:0] HIin, LOin, Zhighin, Zlowin,
    
    // 32-bit data inputs from Program Counter, Memory Data Register, and I/O
    input [31:0] PCin, MDRin, InPort, C_sign_extin
);

    // Internal register to capture the evaluated combinational logic output
    reg [31:0] q;

    // Combinational multiplexing block mapping the 5-bit select code to the physical hardware inputs
    always @(*) begin
        case (sel)
            5'd0:  q = R0in;
            5'd1:  q = R1in;
            5'd2:  q = R2in;
            5'd3:  q = R3in;
            5'd4:  q = R4in;
            5'd5:  q = R5in;
            5'd6:  q = R6in;
            5'd7:  q = R7in;
            5'd8:  q = R8in;
            5'd9:  q = R9in;
            5'd10: q = R10in;
            5'd11: q = R11in;
            5'd12: q = R12in;
            5'd13: q = R13in;
            5'd14: q = R14in;
            5'd15: q = R15in;
            5'd16: q = HIin;
            5'd17: q = LOin;
            5'd18: q = Zhighin;
            5'd19: q = Zlowin;
            5'd20: q = PCin;
            5'd21: q = MDRin;
            5'd22: q = InPort;
            5'd23: q = C_sign_extin;
            
            // Default assignment to forcefully prevent inferred latches and stabilize the bus
            default: q = 32'd0; 
        endcase
    end

    // Continuously drive the evaluated register value onto the main datapath bus
    assign BusMuxOut = q;

endmodule