`timescale 1ns/10ps

// CON FF Logic: Determines whether the correct condition has been met to execute a branch instruction.
// It evaluates the numerical value on the datapath bus against the condition specified in the IR.
module con_ff_logic (
    input clk,
    input CONin,             // Enable signal generated by the Control Unit
    input [1:0] IR_C2,       // The lower two bits of the branch condition field, driven by IR[20:19]
    input [31:0] BusMuxOut,  // Evaluates the numerical value of the selected register currently on the Bus
    output reg CON           // The condition flip-flop output sent back to the Control Unit
);

    // Internal wires representing the four distinct branching conditions
    wire eq_zero, neq_zero, pos, neg;
    
    // The selected condition evaluated by the multiplexer to be fed into the D flip-flop
    wire D_in;

    // --------------------------------------------------------------------
    // Condition Evaluation Logic
    // --------------------------------------------------------------------
    // The hardware evaluates the 32-bit bus to determine its mathematical state
    assign eq_zero  = (BusMuxOut == 32'b0); // True if the bus is exactly zero
    assign neq_zero = (BusMuxOut != 32'b0); // True if the bus contains any non-zero value
    
    // In two's complement, the Most Significant Bit (BusMuxOut[1]) represents the sign.
    // An inverted MSB indicates a positive number (>= 0), while a direct MSB indicates a negative number (< 0).
    assign pos      = ~BusMuxOut[1];       
    assign neg      = BusMuxOut[1];        

    // --------------------------------------------------------------------
    // 4-to-1 Multiplexer (Decoder)
    // --------------------------------------------------------------------
    // Decodes the IR[20:19] field to select which evaluated condition gets routed to the flip-flop.
    assign D_in = (IR_C2 == 2'b00) ? eq_zero :   // brzr: Branch if zero
                  (IR_C2 == 2'b01) ? neq_zero :  // brnz: Branch if nonzero
                  (IR_C2 == 2'b10) ? pos :       // brpl: Branch if positive
                  (IR_C2 == 2'b11) ? neg :       // brmi: Branch if negative
                  1'b0;

    // --------------------------------------------------------------------
    // Synchronous D Flip-Flop
    // --------------------------------------------------------------------
    // The evaluated condition is latched strictly when the Control Unit asserts the CONin enable signal.
    always @(posedge clk) begin
        if (CONin) begin
            CON <= D_in;
        end
    end

endmodule