onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_phase3/clk
add wave -noupdate /tb_phase3/reset
add wave -noupdate /tb_phase3/stop
add wave -noupdate /tb_phase3/InPort_data_in
add wave -noupdate /tb_phase3/OutPort_data_out
add wave -noupdate /tb_phase3/PC_out
add wave -noupdate /tb_phase3/IR_out
add wave -noupdate /tb_phase3/MAR_out
add wave -noupdate /tb_phase3/MDR_out
add wave -noupdate /tb_phase3/HI_out
add wave -noupdate /tb_phase3/LO_out
add wave -noupdate /tb_phase3/Zhigh_out
add wave -noupdate /tb_phase3/Zlow_out
add wave -noupdate /tb_phase3/R0_out
add wave -noupdate /tb_phase3/R1_out
add wave -noupdate /tb_phase3/R2_out
add wave -noupdate /tb_phase3/R3_out
add wave -noupdate /tb_phase3/R4_out
add wave -noupdate /tb_phase3/R5_out
add wave -noupdate /tb_phase3/R6_out
add wave -noupdate /tb_phase3/R7_out
add wave -noupdate /tb_phase3/R8_out
add wave -noupdate /tb_phase3/R9_out
add wave -noupdate /tb_phase3/R10_out
add wave -noupdate /tb_phase3/R11_out
add wave -noupdate /tb_phase3/R12_out
add wave -noupdate /tb_phase3/R13_out
add wave -noupdate /tb_phase3/R14_out
add wave -noupdate /tb_phase3/R15_out
add wave -noupdate /tb_phase3/DUT/IR/Q
add wave -noupdate /tb_phase3/DUT/PC/Q
add wave -noupdate /tb_phase3/DUT/MDR_unit/mdr_internal_reg/Q
add wave -noupdate /tb_phase3/DUT/MAR/Q
add wave -noupdate /tb_phase3/DUT/R0/Q
add wave -noupdate /tb_phase3/DUT/R1/Q
add wave -noupdate /tb_phase3/DUT/R2/Q
add wave -noupdate /tb_phase3/DUT/R3/Q
add wave -noupdate /tb_phase3/DUT/R4/Q
add wave -noupdate /tb_phase3/DUT/R5/Q
add wave -noupdate /tb_phase3/DUT/R6/Q
add wave -noupdate /tb_phase3/DUT/R7/Q
add wave -noupdate /tb_phase3/DUT/R8/Q
add wave -noupdate /tb_phase3/DUT/R9/Q
add wave -noupdate /tb_phase3/DUT/R10/Q
add wave -noupdate /tb_phase3/DUT/R11/Q
add wave -noupdate /tb_phase3/DUT/R12/Q
add wave -noupdate /tb_phase3/DUT/R13/Q
add wave -noupdate /tb_phase3/DUT/R14/Q
add wave -noupdate /tb_phase3/DUT/R15/Q
add wave -noupdate /tb_phase3/DUT/HI/Q
add wave -noupdate /tb_phase3/DUT/LO/Q
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {282033 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {500 ns}
